language: objective-c
os: osx

before_install:
  - brew update
  - brew tap oclint/formulae
  - brew install oclint

script:
  - xcodebuild | tee xcodebuild.log
  - oclint-xcodebuild
  - oclint-json-compilation-database | sed 's/\(.*\.\m\{1,2\}:[0-9]*:[0-9]*:\)/\1 warning:/'
